name: fluttercms
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3


  ## App State Management
  provider: ^4.0.1


  ## 언어화 위젯
  flutter_localizations:
    sdk: flutter


  firebase_auth: ^0.16.1
  google_sign_in: ^4.4.6
  cloud_firestore: ^0.13.6


  ## 이미지 캐시 및 URL 오류 방지
  cached_network_image: ^2.2.0+1



  ## 날짜(생일) 선택
  flutter_datetime_picker: ^1.3.8

  ## 캐시에 필요
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2


  ## 컴포넌트를 Android 와 iOS 에 맞춰 다르게 보여주는 위젯.
  flutter_platform_widgets: ^0.32.5


  ## Human readable time
  time_formatter: ^1.0.0

  ## 유틸리티 함수
  validators: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:    
    - lib/flutterbase/assets/images/user-icon.png
